# Generated by Django 4.2 on 2023-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_runningbatches_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=5)),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="runningbatches",
            name="nsubs",
            field=models.IntegerField(max_length=20),
        ),
    ]
